const flags: { [currencyAbbreviation: string]: string[] } = {
  AED: ['ae.svg'],
  AFN: ['af.svg'],
  ALL: ['al.svg'],
  AMD: ['am.svg'],
  ANG: ['cw.svg', 'sx.svg'],
  AOA: ['ao.svg'],
  ARS: ['ar.svg'],
  AUD: ['au.svg', 'cc.svg', 'cx.svg', 'ki.svg', 'nf.svg', 'nr.svg', 'tv.svg', 'hm.svg'],
  AWG: ['aw.svg'],
  AZN: ['az.svg'],
  BAM: ['ba.svg'],
  BBD: ['bb.svg'],
  BDT: ['bd.svg'],
  BGN: ['bg.svg'],
  BHD: ['bh.svg'],
  BIF: ['bi.svg'],
  BMD: ['bm.svg'],
  BND: ['bn.svg'],
  BOB: ['bo.svg'],
  BRL: ['br.svg'],
  BSD: ['bs.svg'],
  BTC: ['sv.svg', 'bitcoin.jpg'],
  BTN: ['bt.svg'],
  BWP: ['bw.svg'],
  BYN: ['by.svg'],
  BYR: ['by.svg'],
  BZD: ['bz.svg'],
  CAD: ['ca.svg'],
  CDF: ['cd.svg', 'cg.svg'],
  CHF: ['ch.svg', 'li.svg'],
  CLF: ['cl.svg'],
  CLP: ['cl.svg'],
  CNY: ['cn.svg'],
  COP: ['co.svg'],
  CRC: ['cr.svg'],
  CUC: ['cu.svg'],
  CUP: ['cu.svg'],
  CVE: ['cv.svg'],
  CZK: ['cz.svg'],
  DJF: ['dj.svg'],
  DKK: ['dk.svg', 'fo.svg', 'gl.svg'],
  DOP: ['dm.svg', 'do.svg'],
  DZD: ['dz.svg'],
  EGP: ['eg.svg'],
  ERN: ['er.svg'],
  ETB: ['et.svg'],
  EUR: [
    'ad.svg',
    'at.svg',
    'ax.svg',
    'be.svg',
    'bl.svg',
    'cy.svg',
    'de.svg',
    'ee.svg',
    'es.svg',
    'fi.svg',
    'fr.svg',
    'gf.svg',
    'gp.svg',
    'gr.svg',
    'ie.svg',
    'it.svg',
    'lt.svg',
    'lu.svg',
    'lv.svg',
    'mc.svg',
    'me.svg',
    'mf.svg',
    'mq.svg',
    'mt.svg',
    'nl.svg',
    'pm.svg',
    'pt.svg',
    're.svg',
    'si.svg',
    'sk.svg',
    'sm.svg',
    'tf.svg',
    'va.svg',
    'yt.svg',
  ],
  FJD: ['fj.svg'],
  FKP: ['fk.svg'],
  GBP: ['gb.svg', 'gg.svg', 'im.svg', 'je.svg'],
  GEL: ['ge.svg', 'gs.svg'],
  GGP: ['gg.svg'],
  GHS: ['gh.svg'],
  GIP: ['gi.svg'],
  GMD: ['gm.svg'],
  GNF: ['gn.svg'],
  GTQ: ['gt.svg'],
  GYD: ['gy.svg'],
  HKD: ['hk.svg'],
  HNL: ['hn.svg'],
  HRK: ['hr.svg'],
  HTG: ['ht.svg'],
  HUF: ['hu.svg'],
  IDR: ['id.svg'],
  ILS: ['il.svg', 'ps.svg'],
  IMP: ['im.svg'],
  INR: ['in.svg'],
  IQD: ['iq.svg'],
  IRR: ['ir.svg'],
  ISK: ['is.svg'],
  JEP: ['je.svg'],
  JMD: ['jm.svg'],
  JOD: ['jo.svg'],
  JPY: ['jp.svg'],
  KES: ['ke.svg'],
  KGS: ['kg.svg'],
  KHR: ['kh.svg'],
  KMF: ['km.svg'],
  KPW: ['kp.svg'],
  KRW: ['kr.svg'],
  KWD: ['kw.svg'],
  KYD: ['ky.svg'],
  KZT: ['kz.svg'],
  LAK: ['la.svg'],
  LBP: ['lb.svg'],
  LKR: ['lk.svg'],
  LRD: ['lr.svg'],
  LSL: ['ls.svg'],
  LTL: ['lt.svg'],
  LVL: ['lv.svg'],
  LYD: ['ly.svg'],
  MAD: ['eh.svg', 'ma.svg'],
  MDL: ['md.svg'],
  MGA: ['mg.svg'],
  MKD: ['mk.svg'],
  MMK: ['mm.svg'],
  MNT: ['mn.svg'],
  MOP: ['mo.svg'],
  MRO: ['eh.svg', 'mr.svg'],
  MUR: ['mu.svg'],
  MVR: ['mv.svg'],
  MWK: ['mw.svg'],
  MXN: ['mx.svg'],
  MYR: ['my.svg'],
  MZN: ['mz.svg'],
  NAD: ['na.svg'],
  NGN: ['ne.svg', 'ng.svg'],
  NIO: ['ni.svg'],
  NOK: ['bv.svg', 'no.svg', 'sj.svg'],
  NPR: ['np.svg'],
  NZD: ['ck.svg', 'nu.svg', 'nz.svg', 'pn.svg', 'tk.svg'],
  OMR: ['om.svg'],
  PAB: ['pa.svg'],
  PEN: ['pe.svg'],
  PGK: ['pg.svg'],
  PHP: ['ph.svg'],
  PKR: ['pk.svg'],
  PLN: ['pl.svg'],
  PYG: ['py.svg'],
  QAR: ['qa.svg'],
  RON: ['ro.svg'],
  RSD: ['rs.svg'],
  RUB: ['ru.svg'],
  RWF: ['rw.svg'],
  SAR: ['sa.svg'],
  SBD: ['sb.svg'],
  SCR: ['sc.svg'],
  SDG: ['sd.svg'],
  SEK: ['se.svg'],
  SGD: ['sg.svg'],
  SHP: ['sh.svg'],
  SLL: ['sl.svg'],
  SOS: ['so.svg'],
  SRD: ['sr.svg'],
  STD: ['st.svg'],
  SVC: ['sv.svg'],
  SYP: ['sy.svg'],
  SZL: ['sz.svg'],
  THB: ['th.svg'],
  TJS: ['tj.svg'],
  TMT: ['tm.svg'],
  TND: ['tn.svg'],
  TOP: ['to.svg'],
  TRY: ['tr.svg'],
  TTD: ['tt.svg'],
  TWD: ['tw.svg'],
  TZS: ['tz.svg'],
  UAH: ['ua.svg'],
  UGX: ['ug.svg'],
  USD: [
    'us.svg',
    'as.svg',
    'bq.svg',
    'ec.svg',
    'fm.svg',
    'gu.svg',
    'io.svg',
    'mh.svg',
    'mp.svg',
    'pr.svg',
    'pw.svg',
    'tc.svg',
    'tl.svg',
    'vg.svg',
    'vi.svg',
    'ws.svg',
    'aq.svg',
  ],
  UYU: ['uy.svg'],
  UZS: ['uz.svg'],
  VEF: ['vn.svg'],
  VND: ['vn.svg'],
  VUV: ['vu.svg'],
  WST: ['ws.svg'],
  XAF: ['cf.svg', 'cm.svg', 'ga.svg', 'gq.svg', 'td.svg'],
  XAG: ['silver.jpg'],
  XAU: ['gold.jpg'],
  XCD: ['ag.svg', 'ai.svg', 'gd.svg', 'kn.svg', 'lc.svg', 'ms.svg', 'vc.svg'],
  XDR: ['imf.svg'],
  XOF: ['bf.svg', 'bj.svg', 'ci.svg', 'gw.svg', 'ml.svg', 'sn.svg', 'tg.svg'],
  XPF: ['nc.svg', 'pf.svg', 'wf.svg'],
  YER: ['ye.svg'],
  ZAR: ['za.svg'],
  ZMK: ['zm.svg'],
  ZMW: ['zm.svg'],
  ZWL: ['zw.svg'],
};
export default flags;
