const PortugueseTitles: { [key: string]: string } = {
  'United-Arab-Emirates-Dirham': 'Dirrã Dos Emirados Árabes Unidos',
  'Afghan-Afghani': 'Afegão Afegão',
  'Albanian-Lek': 'Lek Albanês',
  'Armenian-Dram': 'Dram Armênio',
  'Netherlands-Antillean-Guilder': 'Guilder Das Antilhas Holandesas',
  'Angolan-Kwanza': 'Kwanza Angolano',
  'Argentine-Peso': 'Peso Argentino',
  'Australian-Dollar': 'Dólar Australiano',
  'Aruban-Florin': 'Florim De Aruba',
  'Azerbaijani-Manat': 'Manat Do Azerbaijão',
  'Bosnia-Herzegovina-Convertible-Mark': 'Marco Conversível Da Bósnia-Herzegovina',
  'Barbadian-Dollar': 'Dólar De Barbados',
  'Bangladeshi-Taka': 'Taka De Bangladesh',
  'Bulgarian-Lev': 'Lev Búlgaro',
  'Bahraini-Dinar': 'Dinar Do Bahrein',
  'Burundian-Franc': 'Franco Do Burundi',
  'Bermudan-Dollar': 'Dólar Das Bermudas',
  'Brunei-Dollar': 'Dólar De Brunei',
  'Bolivian-Boliviano': 'Boliviano Boliviano',
  'Brazilian-Real': 'Real Brasileiro',
  'Bahamian-Dollar': 'Dólar Das Bahamas',
  Bitcoin: 'Bitcoin',
  'Bhutanese-Ngultrum': 'Ngultrum Butanês',
  'Botswanan-Pula': 'Botsuana Pula',
  'New-Belarusian-Ruble': 'Novo Rublo Bielorrusso',
  'Belarusian-Ruble': 'Rublo Bielorrusso',
  'Belize-Dollar': 'Dólar De Belize',
  'Canadian-Dollar': 'Dólar Canadense',
  'Congolese-Franc': 'Franco Congolês',
  'Swiss-Franc': 'Franco Suíço',
  'Chilean-Unit-of-Account-(UF)': 'Unidade De Conta Do Chile (Uf)',
  'Chilean-Peso': 'Peso Chileno',
  'Chinese-Yuan': 'Yuan Chinês',
  'Colombian-Peso': 'Peso Colombiano',
  'Costa-Rican-Colón': 'Colón Da Costa Rica',
  'Cuban-Convertible-Peso': 'Peso Cubano Conversível',
  'Cuban-Peso': 'Peso Cubano',
  'Cape-Verdean-Escudo': 'Escudo Cabo-Verdiano',
  'Czech-Republic-Koruna': 'República Tcheca Coroa',
  'Djiboutian-Franc': 'Franco Djibutiano',
  'Danish-Krone': 'Coroa Dinamarquesa',
  'Dominican-Peso': 'Peso Dominicano',
  'Algerian-Dinar': 'Dinar Argelino',
  'Egyptian-Pound': 'Libra Egípcia',
  'Eritrean-Nakfa': 'Nakfa Da Eritreia',
  'Ethiopian-Birr': 'Birr Etíope',
  Euro: 'Euro',
  'Fijian-Dollar': 'Dólar Fijiano',
  'Falkland-Islands-Pound': 'Libra Das Malvinas',
  'British-Pound-Sterling': 'Libra Esterlina Britânica',
  'Georgian-Lari': 'Lari Georgiano',
  'Guernsey-Pound': 'Libra De Guernsey',
  'Ghanaian-Cedi': 'Cedi Ganês',
  'Gibraltar-Pound': 'Libra De Gibraltar',
  'Gambian-Dalasi': 'Dalasi Da Gâmbia',
  'Guinean-Franc': 'Franco Guineense',
  'Guatemalan-Quetzal': 'Quetzal Da Guatemala',
  'Guyanaese-Dollar': 'Dólar Guianense',
  'Hong-Kong-Dollar': 'Dólar De Hong Kong',
  'Honduran-Lempira': 'Lempira Hondurenha',
  'Croatian-Kuna': 'Kuna Croata',
  'Haitian-Gourde': 'Gourde Haitiano',
  'Hungarian-Forint': 'Forint Húngaro',
  'Indonesian-Rupiah': 'Rupia Indonésia',
  'Israeli-New-Sheqel': 'Novo Shekel Israelense',
  'Manx-pound': 'Libra Manx',
  'Indian-Rupee': 'Rupia Indiana',
  'Iraqi-Dinar': 'Dinar Iraquiano',
  'Iranian-Rial': 'Rial Iraniano',
  'Icelandic-Króna': 'Coroa Islandesa',
  'Jersey-Pound': 'Libra De Jersey',
  'Jamaican-Dollar': 'Dólar Jamaicano',
  'Jordanian-Dinar': 'Dinar Jordaniano',
  'Japanese-Yen': 'Yen Japonês',
  'Kenyan-Shilling': 'Xelim Queniano',
  'Kyrgystani-Som': 'Som Quirguistão',
  'Cambodian-Riel': 'Riel Cambojano',
  'Comorian-Franc': 'Franco Comoriano',
  'North-Korean-Won': 'Won Norte-Coreano',
  'South-Korean-Won': 'Won Sul-Coreano',
  'Kuwaiti-Dinar': 'Dinar Do Kuwait',
  'Cayman-Islands-Dollar': 'Dólar Das Ilhas Cayman',
  'Kazakhstani-Tenge': 'Tenge Do Cazaquistão',
  'Laotian-Kip': 'Kip Do Laos',
  'Lebanese-Pound': 'Libra Libanesa',
  'Sri-Lankan-Rupee': 'Rupia Do Sri Lanka',
  'Liberian-Dollar': 'Dólar Liberiano',
  'Lesotho-Loti': 'Lesoto Loti',
  'Lithuanian-Litas': 'Litas Lituanas',
  'Latvian-Lats': 'Lats Letão',
  'Libyan-Dinar': 'Dinar Líbio',
  'Moroccan-Dirham': 'Dirrã Marroquino',
  'Moldovan-Leu': 'Leu Moldavo',
  'Malagasy-Ariary': 'Ariary Malgaxe',
  'Macedonian-Denar': 'Dinar Macedônio',
  'Myanma-Kyat': 'Myanma Kyat',
  'Mongolian-Tugrik': 'Tugrik Da Mongólia',
  'Macanese-Pataca': 'Pataca Macaense',
  'Mauritanian-Ouguiya': 'Ouguiya Da Mauritânia',
  'Mauritian-Rupee': 'Rupia Mauriciana',
  'Maldivian-Rufiyaa': 'Rufiyaa Das Maldivas',
  'Malawian-Kwacha': 'Kwacha Do Malawi',
  'Mexican-Peso': 'Peso Mexicano',
  'Malaysian-Ringgit': 'Ringgit Da Malásia',
  'Mozambican-Metical': 'Metical Moçambicano',
  'Namibian-Dollar': 'Dólar Namibiano',
  'Nigerian-Naira': 'Naira Nigeriana',
  'Nicaraguan-Córdoba': 'Córdoba Da Nicarágua',
  'Norwegian-Krone': 'Coroa Norueguesa',
  'Nepalese-Rupee': 'Rupia Nepalesa',
  'New-Zealand-Dollar': 'Dólar Da Nova Zelândia',
  'Omani-Rial': 'Rial De Omã',
  'Panamanian-Balboa': 'Balboa Panamenho',
  'Peruvian-Nuevo-Sol': 'Nuevo Sol Peruano',
  'Papua-New-Guinean-Kina': 'Papua Nova Guiné Kina',
  'Philippine-Peso': 'Peso Filipino',
  'Pakistani-Rupee': 'Rupia Paquistanesa',
  'Polish-Zloty': 'Zloty Polonês',
  'Paraguayan-Guarani': 'Guarani Paraguaio',
  'Qatari-Rial': 'Rial Catarense',
  'Romanian-Leu': 'Leu Romeno',
  'Serbian-Dinar': 'Dinar Sérvio',
  'Russian-Ruble': 'Rublo Russo',
  'Rwandan-Franc': 'Franco Ruandês',
  'Saudi-Riyal': 'Rial Saudita',
  'Solomon-Islands-Dollar': 'Dólar Das Ilhas Salomão',
  'Seychellois-Rupee': 'Rúpia Seichelense',
  'Sudanese-Pound': 'Libra Sudanesa',
  'Swedish-Krona': 'Coroa Sueca',
  'Singapore-Dollar': 'Dólar De Singapura',
  'Saint-Helena-Pound': 'Libra De Santa Helena',
  'Sierra-Leonean-Leone': 'Leão Da Serra Leoa',
  'Somali-Shilling': 'Xelim Da Somália',
  'Surinamese-Dollar': 'Dólar Do Suriname',
  'São-Tomé-and-Príncipe-Dobra': 'São Tomé E Príncipe Dobra',
  'Salvadoran-Colón': 'Colón Salvadorenho',
  'Syrian-Pound': 'Libra Síria',
  'Swazi-Lilangeni': 'Suazi Lilangeni',
  'Thai-Baht': 'Baht Tailandês',
  'Tajikistani-Somoni': 'Tajiquistão Somoni',
  'Turkmenistani-Manat': 'Manat Do Turcomenistão',
  'Tunisian-Dinar': 'Dinar Tunisiano',
  'Tongan-Paʻanga': "Tonga Pa'anga",
  'Turkish-Lira': 'Lira Turca',
  'Trinidad-and-Tobago-Dollar': 'Dólar De Trinidad E Tobago',
  'New-Taiwan-Dollar': 'Novo Dólar Taiwanês',
  'Tanzanian-Shilling': 'Xelim Da Tanzânia',
  'Ukrainian-Hryvnia': 'Hryvnia Ucraniano',
  'Ugandan-Shilling': 'Xelim De Uganda',
  'United-States-Dollar': 'Dolar Americano',
  'Uruguayan-Peso': 'Peso Uruguaio',
  'Uzbekistan-Som': 'Som Do Uzbequistão',
  'Venezuelan-Bolívar-Fuerte': 'Venezuelano Bolívar Forte',
  'Vietnamese-Dong': 'Dong Vietnamita',
  'Vanuatu-Vatu': 'Vanuatu Vatu',
  'Samoan-Tala': 'Tala Samoano',
  'CFA-Franc-BEAC': 'Franco Cfa Beac',
  'Silver-(troy-ounce)': 'Prata (Onça Troy)',
  'Gold-(troy-ounce)': 'Ouro (Onça Troy)',
  'East-Caribbean-Dollar': 'Dólar Do Caribe Oriental',
  'Special-Drawing-Rights': 'Direitos Especiais De Saque',
  'CFA-Franc-BCEAO': 'Franco Cfa Bceao',
  'CFP-Franc': 'Franco Cfp',
  'Yemeni-Rial': 'Rial Iemenita',
  'South-African-Rand': 'Rand Sul-Africano',
  'Zambian-Kwacha-(pre-2013)': 'Kwacha Da Zâmbia (Pré-2013)',
  'Zambian-Kwacha': 'Kwacha Da Zâmbia',
  'Zimbabwean-Dollar': 'Dólar Do Zimbábue',
};
export default PortugueseTitles;
