const TranslatedTitles: { [userLocale: string]: { [key: string]: string } } = {
  pt: {
    AED: 'Dirrã Dos Emirados Árabes Unidos',
    AFN: 'Afegão Afegão',
    ALL: 'Lek Albanês',
    AMD: 'Dram Armênio',
    ANG: 'Guilder Das Antilhas Holandesas',
    AOA: 'Kwanza Angolano',
    ARS: 'Peso Argentino',
    AUD: 'Dólar Australiano',
    AWG: 'Florim De Aruba',
    AZN: 'Manat Do Azerbaijão',
    BAM: 'Marco Conversível Da Bósnia-Herzegovina',
    BBD: 'Dólar De Barbados',
    BDT: 'Taka De Bangladesh',
    BGN: 'Lev Búlgaro',
    BHD: 'Dinar Do Bahrein',
    BIF: 'Franco Do Burundi',
    BMD: 'Dólar Das Bermudas',
    BND: 'Dólar De Brunei',
    BOB: 'Boliviano Boliviano',
    BRL: 'Real Brasileiro',
    BSD: 'Dólar Das Bahamas',
    BTC: 'Bitcoin',
    BTN: 'Ngultrum Butanês',
    BWP: 'Botsuana Pula',
    BYN: 'Novo Rublo Bielorrusso',
    BYR: 'Rublo Bielorrusso',
    BZD: 'Dólar De Belize',
    CAD: 'Dólar Canadense',
    CDF: 'Franco Congolês',
    CHF: 'Franco Suíço',
    CLF: 'Unidade De Conta Do Chile (Uf)',
    CLP: 'Peso Chileno',
    CNY: 'Yuan Chinês',
    COP: 'Peso Colombiano',
    CRC: 'Colón Da Costa Rica',
    CUC: 'Peso Cubano Conversível',
    CUP: 'Peso Cubano',
    CVE: 'Escudo Cabo-Verdiano',
    CZK: 'República Tcheca Coroa',
    DJF: 'Franco Djibutiano',
    DKK: 'Coroa Dinamarquesa',
    DOP: 'Peso Dominicano',
    DZD: 'Dinar Argelino',
    EGP: 'Libra Egípcia',
    ERN: 'Nakfa Da Eritreia',
    ETB: 'Birr Etíope',
    EUR: 'Euro',
    FJD: 'Dólar Fijiano',
    FKP: 'Libra Das Malvinas',
    GBP: 'Libra Esterlina Britânica',
    GEL: 'Lari Georgiano',
    GGP: 'Libra De Guernsey',
    GHS: 'Cedi Ganês',
    GIP: 'Libra De Gibraltar',
    GMD: 'Dalasi Da Gâmbia',
    GNF: 'Franco Guineense',
    GTQ: 'Quetzal Da Guatemala',
    GYD: 'Dólar Guianense',
    HKD: 'Dólar De Hong Kong',
    HNL: 'Lempira Hondurenha',
    HRK: 'Kuna Croata',
    HTG: 'Gourde Haitiano',
    HUF: 'Forint Húngaro',
    IDR: 'Rupia Indonésia',
    ILS: 'Novo Shekel Israelense',
    IMP: 'Libra Manx',
    INR: 'Rupia Indiana',
    IQD: 'Dinar Iraquiano',
    IRR: 'Rial Iraniano',
    ISK: 'Coroa Islandesa',
    JEP: 'Libra De Jersey',
    JMD: 'Dólar Jamaicano',
    JOD: 'Dinar Jordaniano',
    JPY: 'Yen Japonês',
    KES: 'Xelim Queniano',
    KGS: 'Som Quirguistão',
    KHR: 'Riel Cambojano',
    KMF: 'Franco Comoriano',
    KPW: 'Won Norte-Coreano',
    KRW: 'Won Sul-Coreano',
    KWD: 'Dinar Do Kuwait',
    KYD: 'Dólar Das Ilhas Cayman',
    KZT: 'Tenge Do Cazaquistão',
    LAK: 'Kip Do Laos',
    LBP: 'Libra Libanesa',
    LKR: 'Rupia Do Sri Lanka',
    LRD: 'Dólar Liberiano',
    LSL: 'Lesoto Loti',
    LTL: 'Litas Lituanas',
    LVL: 'Lats Letão',
    LYD: 'Dinar Líbio',
    MAD: 'Dirrã Marroquino',
    MDL: 'Leu Moldavo',
    MGA: 'Ariary Malgaxe',
    MKD: 'Dinar Macedônio',
    MMK: 'Myanma Kyat',
    MNT: 'Tugrik Da Mongólia',
    MOP: 'Pataca Macaense',
    MRO: 'Ouguiya Da Mauritânia',
    MUR: 'Rupia Mauriciana',
    MVR: 'Rufiyaa Das Maldivas',
    MWK: 'Kwacha Do Malawi',
    MXN: 'Peso Mexicano',
    MYR: 'Ringgit Da Malásia',
    MZN: 'Metical Moçambicano',
    NAD: 'Dólar Namibiano',
    NGN: 'Naira Nigeriana',
    NIO: 'Córdoba Da Nicarágua',
    NOK: 'Coroa Norueguesa',
    NPR: 'Rupia Nepalesa',
    NZD: 'Dólar Da Nova Zelândia',
    OMR: 'Rial De Omã',
    PAB: 'Balboa Panamenho',
    PEN: 'Nuevo Sol Peruano',
    PGK: 'Papua Nova Guiné Kina',
    PHP: 'Peso Filipino',
    PKR: 'Rupia Paquistanesa',
    PLN: 'Zloty Polonês',
    PYG: 'Guarani Paraguaio',
    QAR: 'Rial Catarense',
    RON: 'Leu Romeno',
    RSD: 'Dinar Sérvio',
    RUB: 'Rublo Russo',
    RWF: 'Franco Ruandês',
    SAR: 'Rial Saudita',
    SBD: 'Dólar Das Ilhas Salomão',
    SCR: 'Rúpia Seichelense',
    SDG: 'Libra Sudanesa',
    SEK: 'Coroa Sueca',
    SGD: 'Dólar De Singapura',
    SHP: 'Libra De Santa Helena',
    SLL: 'Leão Da Serra Leoa',
    SOS: 'Xelim Da Somália',
    SRD: 'Dólar Do Suriname',
    STD: 'São Tomé E Príncipe Dobra',
    SVC: 'Colón Salvadorenho',
    SYP: 'Libra Síria',
    SZL: 'Suazi Lilangeni',
    THB: 'Baht Tailandês',
    TJS: 'Tajiquistão Somoni',
    TMT: 'Manat Do Turcomenistão',
    TND: 'Dinar Tunisiano',
    TOP: "Tonga Pa'anga",
    TRY: 'Lira Turca',
    TTD: 'Dólar De Trinidad E Tobago',
    TWD: 'Novo Dólar Taiwanês',
    TZS: 'Xelim Da Tanzânia',
    UAH: 'Hryvnia Ucraniano',
    UGX: 'Xelim De Uganda',
    USD: 'Dolar Americano',
    UYU: 'Peso Uruguaio',
    UZS: 'Som Do Uzbequistão',
    VEF: 'Venezuelano Bolívar Forte',
    VND: 'Dong Vietnamita',
    VUV: 'Vanuatu Vatu',
    WST: 'Tala Samoano',
    XAF: 'Franco Cfa Beac',
    XAG: 'Prata (Onça Troy)',
    XAU: 'Ouro (Onça Troy)',
    XCD: 'Dólar Do Caribe Oriental',
    XDR: 'Direitos Especiais De Saque',
    XOF: 'Franco Cfa Bceao',
    XPF: 'Franco Cfp',
    YER: 'Rial Iemenita',
    ZAR: 'Rand Sul-Africano',
    ZMK: 'Kwacha Da Zâmbia (Pré-2013)',
    ZMW: 'Kwacha Da Zâmbia',
    ZWL: 'Dólar Do Zimbábue',
  },
  es: {
    AED: 'Dírham de los Emiratos Árabes Unidos',
    AFN: 'afgano afgano',
    ALL: 'Lek albanés',
    AMD: 'Dram armenio',
    ANG: 'florín antillano neerlandés',
    AOA: 'Kwanza angoleño',
    ARS: 'peso argentino',
    AUD: 'Dólar australiano',
    AWG: 'florín arubeño',
    AZN: 'manat azerbaiyano',
    BAM: 'Marco bosnioherzegovino',
    BBD: 'Dólar de Barbados',
    BDT: 'Taka de Bangladesh',
    BGN: 'Lev búlgaro',
    BHD: 'dinar bahreiní',
    BIF: 'Franco de Burundi',
    BMD: 'dólar bermudeño',
    BND: 'Dólar de Brunéi',
    BOB: 'boliviano boliviano',
    BRL: 'Real brasileño',
    BSD: 'dólar bahameño',
    BTC: 'Bitcoin',
    BTN: 'Ngultrum butanés',
    BWP: 'Pula de Botsuana',
    BYN: 'nuevo rublo bielorruso',
    BYR: 'rublo bielorruso',
    BZD: 'Dólar de Belice',
    CAD: 'Dolar canadiense',
    CDF: 'franco congoleño',
    CHF: 'Franco suizo',
    CLF: 'Unidad Chilena de Cuenta (UF)',
    CLP: 'peso chileno',
    CNY: 'yuan chino',
    COP: 'peso colombiano',
    CRC: 'colón costarricense',
    CUC: 'Peso Cubano Convertible',
    CUP: 'peso cubano',
    CVE: 'escudo caboverdiano',
    CZK: 'corona checa',
    DJF: 'franco yibutiano',
    DKK: 'corona danesa',
    DOP: 'peso dominicano',
    DZD: 'dinar argelino',
    EGP: 'Libra egipcia',
    ERN: 'Nakfa de Eritrea',
    ETB: 'Birr etíope',
    EUR: 'Euro',
    FJD: 'dólar fiyiano',
    FKP: 'Libra malvinense',
    GBP: 'Libra esterlina',
    GEL: 'Lari georgiano',
    GGP: 'Libra de Guernsey',
    GHS: 'Cedi ghanés',
    GIP: 'Libra gibraltareña',
    GMD: 'Dalasi gambiano',
    GNF: 'franco guineano',
    GTQ: 'Quetzal guatemalteco',
    GYD: 'dólar guyanés',
    HKD: 'Dolar de Hong Kong',
    HNL: 'Lempira hondureño',
    HRK: 'Kuna croata',
    HTG: 'Gourde haitiano',
    HUF: 'florín húngaro',
    IDR: 'rupia indonesia',
    ILS: 'Nuevo séquel israelí',
    IMP: 'Libra manesa',
    INR: 'Rupia india',
    IQD: 'dinar iraquí',
    IRR: 'rial iraní',
    ISK: 'corona islandesa',
    JEP: 'Libra de Jersey',
    JMD: 'dólar jamaiquino',
    JOD: 'dinar jordano',
    JPY: 'Yen japonés',
    KES: 'chelín keniano',
    KGS: 'Som kirguís',
    KHR: 'Riel camboyano',
    KMF: 'franco comorano',
    KPW: 'Won norcoreano',
    KRW: 'Won surcoreano',
    KWD: 'dinar kuwaití',
    KYD: 'Dólar de las Islas Caimán',
    KZT: 'tenge kazajo',
    LAK: 'Kip laosiano',
    LBP: 'Libra libanesa',
    LKR: 'Rupia de Sri Lanka',
    LRD: 'dólar liberiano',
    LSL: 'lesoto loti',
    LTL: 'Litas lituana',
    LVL: 'Lat letón',
    LYD: 'dinar libio',
    MAD: 'Dírham marroquí',
    MDL: 'Leu moldavo',
    MGA: 'Ariary malgache',
    MKD: 'Denar macedonio',
    MMK: 'Kyat de Myanmar',
    MNT: 'Tugrik mongol',
    MOP: 'Pataca de Macao',
    MRO: 'Uguiya mauritana',
    MUR: 'Rupia de Mauricio',
    MVR: 'Rufiyaa de Maldivas',
    MWK: 'Kwacha de Malawi',
    MXN: 'peso mexicano',
    MYR: 'Ringgit malayo',
    MZN: 'Metical mozambiqueño',
    NAD: 'dólar namibio',
    NGN: 'naira nigeriana',
    NIO: 'Córdoba nicaragüense',
    NOK: 'corona noruega',
    NPR: 'rupia nepalí',
    NZD: 'Dolar de Nueva Zelanda',
    OMR: 'Rial omaní',
    PAB: 'balboa panameño',
    PEN: 'Nuevo sol peruano',
    PGK: 'Kina de Papua Nueva Guinea',
    PHP: 'peso filipino',
    PKR: 'rupia paquistaní',
    PLN: 'Zloty polaco',
    PYG: 'guaraní paraguayo',
    QAR: 'Rial qatarí',
    RON: 'leu rumano',
    RSD: 'dinar serbio',
    RUB: 'Rublo ruso',
    RWF: 'franco ruandés',
    SAR: 'rial saudí',
    SBD: 'Dólar de las Islas Salomón',
    SCR: 'Rupia de Seychelles',
    SDG: 'Libra sudanesa',
    SEK: 'Corona sueca',
    SGD: 'Dolar de Singapur',
    SHP: 'Libra de Santa Elena',
    SLL: 'Sierra Leona Leona',
    SOS: 'chelín somalí',
    SRD: 'dólar surinamés',
    STD: 'São Tomé y Príncipe Dobra',
    SVC: 'colón salvadoreño',
    SYP: 'Libra siria',
    SZL: 'Lilangeni suazi',
    THB: 'Baht tailandés',
    TJS: 'Somoni de Tayikistán',
    TMT: 'manat turkmenistán',
    TND: 'dinar tunecino',
    TOP: 'TPaʻanga de Tonga',
    TRY: 'Lira turca',
    TTD: 'Dólar de Trinidad y Tobago',
    TWD: 'Nuevo dólar taiwanés',
    TZS: 'chelín tanzano',
    UAH: 'Grivna ucraniana',
    UGX: 'Chelín ugandés',
    USD: 'Dólar de los Estados Unidos',
    UYU: 'peso uruguayo',
    UZS: 'Som uzbeko',
    VEF: 'Venezolano bolívar fuerte',
    VND: 'Dong vietnamita',
    VUV: 'Vanuatu Vatu',
    WST: 'Tala de Samoa',
    XAF: 'Franco CFA BEAC',
    XAG: 'Plata (onza troy)',
    XAU: 'Oro (onza troy)',
    XCD: 'Dólar del Caribe Oriental',
    XDR: 'Derechos especiales de dibujo',
    XOF: 'Franco CFA BCEAO',
    XPF: 'Franco CFP',
    YER: 'rial yemení',
    ZAR: 'Rand sudafricano',
    ZMK: 'Kwacha zambiano (anterior a 2013)',
    ZMW: 'kwacha zambiano',
    ZWL: 'dólar zimbabuense',
  },
};

export const userLocale = () => {
  const lang =
    navigator && navigator.languages && navigator.languages.length ? navigator.languages[0] : navigator.language;
  return lang.split('-')[0];
};

export const getTranslatedTitle = (currencySymbol: string) => {
  return TranslatedTitles[userLocale()][currencySymbol];
};

export const hasTranslation = () => {
  return TranslatedTitles[userLocale()];
};

export default TranslatedTitles;
